//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MylanCustomizations.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3uqagf2nrt2mm27q3rt45ett")]
        public string ETClientId {
            get {
                return ((string)(this["ETClientId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D5wxtEx6UGNVxgkbyrruJhQV")]
        public string ETClientSecret {
            get {
                return ((string)(this["ETClientSecret"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3ac34660-e42c-4c2e-9f25-c5017b3820e0")]
        public global::System.Guid NewProductDECustomerKey {
            get {
                return ((global::System.Guid)(this["NewProductDECustomerKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d214c45e-731e-4155-8c02-17b934cab91d")]
        public global::System.Guid ProductUpdateCustomerKey {
            get {
                return ((global::System.Guid)(this["ProductUpdateCustomerKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bffdb9d4-4e9a-4b86-b786-c17e1aa6f6b4")]
        public global::System.Guid SubscribersCustomerKey {
            get {
                return ((global::System.Guid)(this["SubscribersCustomerKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("a998bd8c-af0b-487e-bbd3-24e1fbcc2b4f")]
        public global::System.Guid OptInCustomerKey {
            get {
                return ((global::System.Guid)(this["OptInCustomerKey"]));
            }
        }
    }
}
